# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Simon Giebenhain's Academic GitHub Page
tagline: My personal research interests
email: simon.giebenhain@uni-konstanz.de
description: > # this means to ignore newlines until "baseurl:"
  My simple personal website. Everything is on one page and clearly focused on my research interest, 
  as well as, a nice display of my publications.
domain: simongiebenhain.github.io
url: https://simongiebenhain.github.io
baseurl: 
social:
  - https://github.com/SimonGiebenhain
  - https://scholar.google.com/citations?user=_ju3Ex0AAAAJ&hl=en
  - https://www.linkedin.com/in/simon-giebenhain-4792ba170/

plugins:
  - jekyll-seo-tag

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
